### ISSUE TITLE
Memory leak in resolver.cache for subscribe().once()

### ISSUE THREAD

**Issue by efurmantt** [postaljs/postal.js#95]
This is a very nice library.  I have noticed a small issue however.  When publishing in tandem with `subscribe().once()`, there appears to be a memory leak:

    var postal = require('postal');
    postal.subscribe({ channel: 'ch', topic: 't', callback: function() {}}).once();
    postal.publish({ channel: 'ch', topic: 't', data: 'data' });
    var cachedKeys = Object.keys(postal.configuration.resolver.cache).length;
    console.log(cachedKeys)

In this example, one key is cached, even though no subscriptions remain.

Alternatively, consider this code:

    var postal = require('postal');
    for(var i = 0; i < 100; i++) {
         postal.subscribe({ channel: 'c', topic: 't' + 1, callback: function() {} }).once();
         postal.publish({ channel: 'c', topic: 't' + i, data: 'data' })
    }
    var cachedKeys = Object.keys(postal.configuration.resolver.cache).length;
    console.log(cachedKeys)

In this example, a hundred keys are cached for subscriptions that are no longer active.

**Comment by ifandelse** [comment]
I think we're good to close this, given that we merged in #104. Just ping me if you need anything else, thanks!

**Comment by khamasaki** [comment]
Hi, I am running into this as well, and it is still occurring in 1.0.2. I actually tried upgrading from 0.10.3 to 1.0.2 after we noticed a slow memory leak on our production servers, and it has actually gotten worse in my testing.

For some background, we are heavily using postal.request-response as part of our server side architecture. I also upgraded postal.request-response to 0.3.1 to take advantage of the fix there.

I think I traced the problem to the publish method, particularly this line:

https://github.com/postaljs/postal.js/blob/master/lib/postal.js#L469

It seems that even though postal.request-response is sending the header that tells postal to ignore the cache, the publish method is still putting something into the cache. When I perform a memory dump of the server after it has been running for a while, there are a lot of strings being kept in memory that look like this: "e8ad6cd0-7149-4dff-813d-8383ff1d9e1a|3eb0eb18-7eca-43b0-a73d-8dd7c7bdf902", which seems to correspond to the cacheKey being used in the publish method. After several thousand requests this really starts to eat up a lot of memory.

If I replace line 469 with the following:

                cache = [];

the memory problems go away. Clearly, this is not the correct solution to the problem, but it does indicate that I am looking at the right thing.

Would it be possible to have the publish method not put anything in the cache when the resolverNoCache flag is set? The logic involved there with the cacherFn seems a little complex and I am a little hesitant to attempt a fix myself, so if it would be easy for you to implement I'd appreciate it. If not, I can take a crack at it.

**Comment by ifandelse** [comment]
Thank you for the detailed explanation! I will definitely take a look at
get back with you ASAP.

Sent from my iPhone, so just assume that auto-correct mangled my words...

On May 6, 2015, at 2:09 AM, khamasaki <notifications@github.com> wrote:

Hi, I am running into this as well, and it is still occurring in 1.0.2. I
actually tried upgrading from 0.10.3 to 1.0.2 after we noticed a slow
memory leak on our production servers, and it has actually gotten worse in
my testing.

For some background, we are heavily using postal.request-response as part
of our server side architecture. I also upgraded postal.request-response to
0.3.1 to take advantage of the fix there.

I think I traced the problem to the publish method, particularly this line:

https://github.com/postaljs/postal.js/blob/master/lib/postal.js#L469

It seems that even though postal.request-response is sending the header
that tells postal to ignore the cache, the publish method is still putting
something into the cache. When I perform a memory dump of the server after
it has been running for a while, there are a lot of strings being kept in
memory that look like this:
"e8ad6cd0-7149-4dff-813d-8383ff1d9e1a|3eb0eb18-7eca-43b0-a73d-8dd7c7bdf902",
which seems to correspond to the cacheKey being used in the publish method.
After several thousand requests this really starts to eat up a lot of
memory.

If I replace line 469 with the following:

            cache = [];

the memory problems go away. Clearly, this is not the correct solution to
the problem, but it does indicate that I am looking at the right thing.

Would it be possible to have the publish method not put anything in the
cache when the resolverNoCache flag is set? The logic involved there with
the cacherFn seems a little complex and I am a little hesitant to attempt a
fix myself, so if it would be easy for you to implement I'd appreciate it.
If not, I can take a crack at it.

—
Reply to this email directly or view it on GitHub
<https://github.com/postaljs/postal.js/issues/95#issuecomment-99336472>.

**Comment by ifandelse** [comment]
@khamasaki - I think you're right - I'll get an immediate fix together where postal will check for the `resolverNoCache` flag, and then longer-term I may refactor that envelope header name to noCache, etc. (since we're beyond just the resolver's cache at this point). Barring any unforeseen kids waking up, meteorites landing on the house, or me crying that the season of Person of Interest is over, I should have this done sometime tonight....

**Comment by khamasaki** [comment]
@ifandelse - Thanks so much for looking into this so quickly, really appreciate it. Also, fun show, Person of Interest - I'm behind a couple of episodes so not time to mourn for me yet!

**Comment by ifandelse** [comment]
@khamasaki see if that works out for you...thanks!

**Comment by khamasaki** [comment]
Works great, from what I can tell - both the slow leak from 0.10.3 and the somewhat faster leak from 1.0.2 seem to be gone in 1.0.3. Thanks again!
